
import MiniDrawer from '@/Components/Darshboard'
import React from 'react'
import DynamicTable from '@/Components/Table'
import Head from 'next/head';

export const getServerSideProps = async () => {
  let data = [];
  try {
    const res = await fetch("https://monilicsassignment.onrender.com/users/car-email");
    data = await res.json();
    // console.log("Our data", data);
  } catch (error) {
    console.log(error);
  }

  return {
    props: {
      people: data,
    },
  };
};

function Car({ people }) {
//   console.log(people);
  return (
    <>
      <Head>
        <title>Assignment</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    <MiniDrawer>
      <h4>Users whith car of brand “BMW”, “Mercedes” or “Audi” and whose email does not include any digit.</h4>
      <DynamicTable data={people} />
    </MiniDrawer>
    </>
  );
}

export default Car;
